# Defaults for this cop are found here:
# https://github.com/rubocop/rubocop-rspec/blob/master/config/default.yml
#
# Add customizations below.
#
# Ensure to document why we change a default by linking the corresponding PR.
# For example:
#
#     RSpec/AlignLeftLetBrace:
#       Enabled: true
#


# @NOTE: added: "if", "and"
Style/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - and
